// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {configs} from '../models';

export function LoadConfigs():Promise<configs.Config>;

export function SaveConfigs(arg1:string,arg2:string,arg3:string):Promise<void>;
